Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyBlog.Data;
using MyBlog.Models;
using MyBlog.Services;
using MyBlog.Services.Interfaces;
using X.PagedList;

namespace MyBlog.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBlogService _blogService;
        private readonly IImageService _imageService;

        public CategoriesController(ApplicationDbContext context, IBlogService blogService, IImageService imageService)
        {
            _context = context;
            _blogService = blogService;
            _imageService = imageService;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
              return _context.Categories != null ? 
                          View(await _context.Categories.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id, int? pageNum)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            Category? category = await _context.Categories.Include(c => c.BlogPosts).FirstOrDefaultAsync(m => m.Id == id);

            if (category == null)
            {
                return NotFound();
            }

            int pageSize = 3;
            int page = pageNum ?? 1;


            IPagedList<BlogPost> blogPosts = await category.BlogPosts.ToPagedListAsync(page, pageSize);

            ViewData["CategoryName"] = category.Name;
            ViewData["CategoryId"] = category.Id;

            return View(blogPosts);

            
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ImageData,ImageType")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ImageData,ImageType")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    //Set the image data if one has been chosen
                    if (category.ImageFile != null)
                    {
                        //create image service, convert file to byte array and assign it to the imagedata
                        category.ImageData = await _imageService.ConvertFileToByteArrayAsync(category.ImageFile);

                        //Assign the imagetype based on the chosen file
                        category.ImageType = category.ImageFile.ContentType;
                    }
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyBlog.Data;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BlogUser> _userManager;

        public CommentsController(ApplicationDbContext context, UserManager<BlogUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Comments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Comments.Include(c => c.Author).Include(c => c.BlogPost);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Comments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Author)
                .Include(c => c.BlogPost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // GET: Comments/Create
        public IActionResult Create()
        {
            
            ViewData["BlogPostId"] = new SelectList(_context.BlogPosts, "Id", "Title");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Body,BlogPostId")] Comment comment, string? slug)
        {
            ModelState.Remove("AuthorId");

            if (ModelState.IsValid)
            {
                
                comment.AuthorId= _userManager.GetUserId(User);
                comment.Created= DateTime.Now;

                comment.Body = Regex.Replace(comment.Body!, @"<[^>]*>", string.Empty);

                _context.Add(comment);
                await _context.SaveChangesAsync();

                return RedirectToAction("Details", "BlogPosts", new { slug = slug});
            }
           
            return View(comment);
        }

        // GET: Comments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", comment.AuthorId);
            ViewData["BlogPostId"] = new SelectList(_context.BlogPosts, "Id", "Content", comment.BlogPostId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Created,Updated,UpdateReason,Body,AuthorId,BlogPostId")] Comment comment)
        {
            if (id != comment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", comment.AuthorId);
            ViewData["BlogPostId"] = new SelectList(_context.BlogPosts, "Id", "Content", comment.BlogPostId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Comments == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments
                .Include(c => c.Author)
                .Include(c => c.BlogPost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (comment == null)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Comments == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Comments'  is null.");
            }
            var comment = await _context.Comments.FindAsync(id);
            if (comment != null)
            {
                _context.Comments.Remove(comment);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommentExists(int id)
        {
          return (_context.Comments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyBlog.Data;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    public class TagsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TagsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Tags
        public async Task<IActionResult> Index()
        {
              return _context.Tags != null ? 
                          View(await _context.Tags.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Tags'  is null.");
        }

        // GET: Tags/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // GET: Tags/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags.FindAsync(id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Tag tag)
        {
            if (id != tag.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TagExists(tag.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tags == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Tags'  is null.");
            }
            var tag = await _context.Tags.FindAsync(id);
            if (tag != null)
            {
                _context.Tags.Remove(tag);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagExists(int id)
        {
          return (_context.Tags?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_AuthorAreaPartial.cshtml
@inject IImageService _ImageService

<div class="axil-author-area axil-author-banner bg-color-grey">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="about-author">
                    <div class="media">
                        <div class="thumbnail">
                            <a href="#">
                                <img src="@_ImageService.ConvertByteArrayToFile(null, null, DefaultImage.AuthorImage)" alt="Author Images">
                            </a>
                        </div>
                        <div class="media-body">
                            <div class="author-info">
                                <h1 class="title"><a href="#">Adam Berry</a></h1>
                                <span class="b3 subtitle">Software Developer</span>
                            </div>
                            <div class="content">
                                <p class="b1 description">My name is Adam Berry and I am a software developer located in Winston-Salem, North Carolina. I have been learning and practicing building websites and applications including this blog! This blog is a place for me to write about coding topics I am interested in and share them with others. I primarily use JavaScript, C# and .NET to build my webpages and applications. Send me an email or check out my LinkedIn profile if you'd like to get in touch!</p>
                                <ul class="social-share-transparent size-md">
                                    <li><a asp-action="ContactMe" asp-controller="Home"><i class="far fa-envelope"></i></a></li>
                                    <li><a target="_blank" href="https://www.linkedin.com/in/adam-berry-890939246/"><i class="fab fa-linkedin-in"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_BlogCardPartial.cshtml
@model BlogPost
@inject IImageService _ImageService

<div class="content-block post-list-view mt--30">
    <div class="post-thumbnail">
        <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@Model?.Slug">
            <img src="@_ImageService.ConvertByteArrayToFile(Model?.ImageData,Model?.ImageType, DefaultImage.BlogPostImage)" alt="Post Images">
        </a>
    </div>
    <div class="post-content">
        <div class="post-cat">
            <div class="post-cat-list">
                <a class="hover-flip-item-wrapper" href="#">
                    <span class="hover-flip-item">
                        <span data-text="@Model?.Category?.Name">@Model?.Category?.Name</span>
                    </span>
                </a>
            </div>
        </div>
        <h4 class="title">
            <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@Model?.Slug">
                @Model?.Title
            </a>
        </h4>
        <div class="post-meta-wrapper">
            <div class="post-meta">
                <div class="content">
                    <h6 class="post-author-name">
                        <a class="hover-flip-item-wrapper" href="author.html">
                            <span class="hover-flip-item">
                                <span data-text="Adam Berry">Adam Berry</span>
                            </span>
                        </a>
                    </h6>
                    <ul class="post-meta-list">
                        <li>@Model?.Created.ToString("MMM dd, yyyy")</li>
                    </ul>
                </div>
            </div>
            @*    <ul class="social-share-transparent justify-content-end">
            <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
            <li><a href="#"><i class="fab fa-instagram"></i></a></li>
            <li><a href="#"><i class="fab fa-twitter"></i></a></li>
            <li><a href="#"><i class="fas fa-link"></i></a></li>
            </ul>*@
        </div>
    </div>
</div>

Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyBlog</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <link rel="stylesheet" href="~/assets/css/vendor/font-awesome.css">
    <link rel="stylesheet" href="~/assets/css/vendor/slick.css">
    <link rel="stylesheet" href="~/assets/css/vendor/slick-theme.css">
    <link rel="stylesheet" href="~/assets/css/vendor/base.css">
    <link rel="stylesheet" href="~/assets/css/plugins/plugins.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/css/site.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                      
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BlogPosts" asp-action="Index">Blog Posts</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Comments" asp-action="Index">Comments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="Index">Tags</a>
                        </li>                      
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- JS
       ============================================ -->
    <!-- Modernizer JS -->
    <script src="~/assets/js/vendor/modernizr.min.js"></script>
    <!-- jQuery JS -->
    <script src="~/assets/js/vendor/jquery.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="~/assets/js/vendor/slick.min.js"></script>
    <script src="~/assets/js/vendor/tweenmax.min.js"></script>
    <script src="~/assets/js/vendor/js.cookie.js"></script>
    <script src="~/assets/js/vendor/jquery.style.switcher.js"></script>
    <script src="https://kit.fontawesome.com/5f740f3843.js" crossorigin="anonymous"></script>
    <!-- Main JS -->
    <script src="~/assets/js/main.js"></script>
    <script>
        $(function () {
            const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
            const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LogoutPartial.cshtml
<form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "BlogPosts", new { area = "" })"></form>

Views/Shared/_SideBarPartial.cshtml
@inject IImageService _ImageService
@inject IBlogService _BlogService

@{
    IEnumerable<Category> popularCategories = await _BlogService.GetCategoriesAsync();

    popularCategories = popularCategories.OrderByDescending(c => c.BlogPosts.Count).Take(4);

}



<div class="col-lg-4 col-xl-4 mt_md--40 mt_sm--40">
    <div class="sidebar-inner">

        <!-- Start Single Widget  -->
        @foreach(Category category in popularCategories)
        {
        <div class="axil-single-widget widget widget_categories mb--30">
            <ul>
                <li class="cat-item">
                    <a asp-action="Details" asp-controller="Categories" asp-route-id="@category.Id" class="inner">
                        <div class="thumbnail">
                                <img src="@_ImageService.ConvertByteArrayToFile(category.ImageData,category.ImageType, DefaultImage.CategoryImage)" alt="Post Images">
                        </div>
                        <div class="content">
                            <h5 class="title">@category.Name</h5>
                        </div>
                    </a>
                </li>               
            </ul>
        </div>
        }
        <!-- End Single Widget  -->
        <!-- Start Single Widget  -->
        <div class="axil-single-widget widget widget_search mb--30">
            <h5 class="widget-title">Search</h5>
            <form asp-action="SearchIndex" asp-controller="BlogPosts" class="header-search-form d-sm-block d-none">
                <div class="axil-search form-group">
                    <button type="submit" class="search-button"><i class="fal fa-search"></i></button>
                    <input type="text" class="form-control" placeholder="Search" name="searchString">
                </div>
            </form>
        </div>
        <!-- End Single Widget  -->
        <!-- Start Single Widget  -->
        <div class="axil-single-widget widget widget_postlist mb--30">
            <h5 class="widget-title">Popular Blogs</h5>
            <!-- Start Post List  -->
            <div class="post-medium-block">

                <!-- Start Single Post  -->
                @foreach(BlogPost blogPost in await _BlogService.GetPopularBlogPostsAsync(3))
                {
                <div class="content-block post-medium mb--20">
                    <div class="post-thumbnail">
                        <a href="post-details.html">
                            <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@blogPost.Slug">
                            <img src="@_ImageService.ConvertByteArrayToFile(blogPost.ImageData,blogPost.ImageType, DefaultImage.BlogPostImage)" alt="Post Images">
                            </a>
                        </a>
                    </div>
                    <div class="post-content">
                        <h6 class="title">
                            <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@blogPost.Slug">
                                @blogPost.Title
                            </a>
                        </h6>
                        <div class="post-meta">
                            <ul class="post-meta-list">
                                <li>@blogPost.Created.ToString("MMM dd, yyyy")</li>
                            </ul>
                        </div>
                    </div>
                </div>
                }
                <!-- End Single Post  -->


            </div>
            <!-- End Post List  -->

        </div>
        <!-- End Single Widget  -->
        <!-- Start Single Widget  -->
        <div class="axil-single-widget widget widget_social mb--30">
            <h5 class="widget-title">Stay In Touch</h5>
            <!-- Start Post List  -->
            <ul class="social-icon md-size justify-content-center">
          
                <li><a href="https://www.linkedin.com/in/adam-berry-890939246/" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
            </ul>
            <!-- End Post List  -->
        </div>
        <!-- End Single Widget  -->
    </div>
</div>